@startuml
rectangle "autoware" {
  usecase "/awapi/awapi_awiv_adapter_node"
  usecase "/control/vehicle_cmd_gate"
}

rectangle "v2i control function" {
  usecase "/v2i_interface" #LightCoral
  usecase "/vtl_adapter" #LightCoral
  usecase "/v2i_command_muxer" #LightCoral
  rectangle "user-defined/in-vehicle infrastructure device" {
    node "broadcasting device"
  }
  rectangle "user-defined/infrastructure" {
    node "v2i controller[0]" as v2ictl_0
    node "v2i controller[1]" as v2ictl_1
    node "v2i controller[n]" as v2ictl_n
    node "v2i infrastructure[0]" as v2ihw_0
    node "v2i infrastructure[1]" as v2ihw_1
    node "v2i infrastructure[n]" as v2ihw_n
  }
}

rectangle "in-parking task management function" {
    usecase "in_parking_state_manager" #LightCoral
    usecase "in_parking_task_manager" #LightCoral
    usecase "lanelet2_map_parse_service" #LightCoral
}

rectangle "engage function"{
    usecase "engage_relay_service"  #LightCoral
    usecase "/autoware_state_machine" #LightCoral
}

rectangle "cargo loading management function"{
  usecase "cargo_loading_service"  #LightCoral
}

rectangle "ondemand delivery reservation function" {
  rectangle "web.auto" {
    cloud "FMS (Fleet management system)" as FMS
    usecase "Agent (Interface for FMS)" as Agent
  }
  rectangle "user-defined/saas" {
    cloud "on-demand delivery apps" as DeliveryApp
  }
  usecase "/go_interface" #LightCoral
}

rectangle "Shutdown process management function" {
    usecase "/shutdown_manager" #LightCoral
}

rectangle "hmi control function" {
  rectangle "Sound control function" {
    usecase "/ad_sound_manager" #LightCoral
    usecase "/sound_voice_alarm/audio_driver" #LightCoral
    usecase "/sound_bgm/audio_driver" #LightCoral
  }
  rectangle "Lamp control function" {
    usecase "/ad_status_lamp_manager" #LightCoral
    usecase "/warning_lamp_manager" #LightCoral
    usecase "/delivery_reservation_lamp_manager" #LightCoral
  }
  rectangle "Button control function" {
    usecase "/engage_button_manager" #LightCoral
    usecase "/engage_srv_converter" #LightCoral
    usecase "/button_output_selector" #LightCoral
    usecase "/delivery_reservation_button_manager" #LightCoral
  }
  usecase "/dio_ros_driver" as (/dio_ros_driver) #LightCoral

  rectangle "user-defined/in-vehicle HMI devices" {
    node "speaker"
    node "ad_status_lamp"
    node "warning_lamp"
    node "emergency_lamp"
    node "delivery_reservation_lamp"
    node "engage_button"
    node "delivery_reservation_button"
  }
}

(/autoware_state_machine) --> (/go_interface)
(/autoware_state_machine) <-- (/go_interface)

(cargo_loading_service) <-u- (in_parking_state_manager) :/in_parking/state
(cargo_loading_service) -u-> (in_parking_task_manager)
(cargo_loading_service) <--u- (in_parking_task_manager) :/in_parking/task
(in_parking_task_manager) <- (lanelet2_map_parse_service) : /lanelet2_map_parse_service
(in_parking_task_manager) <- (lanelet2_map_parse_service) : /lanelet2_map_parse_service/is_ready
(/vtl_adapter) <- (/v2i_interface) : /v2i/infrastructer_states
(cargo_loading_service) -> (/v2i_command_muxer) : /cargo_loding/infrastructure_commands
(/v2i_command_muxer) -> (/v2i_interface) : /v2i/infrastructer_commands
(/v2i_interface) -> (cargo_loading_service) : /v2i/infrastructer_states

(in_parking_state_manager) -> (engage_relay_service) : \n/in_parkinge/set/auto_engage
(engage_relay_service) -> (/autoware_state_machine) : /api/external/set/engage

(/v2i_interface) -[hidden] (/ad_sound_manager)
(/engage_srv_converter) -[hidden] (/v2i_interface)
(/ad_sound_manager) -[hidden] (/engage_srv_converter)
(broadcasting device) -[hidden] (speaker)

(/delivery_reservation_lamp_manager) --[hidden] (delivery_reservation_lamp)
(/ad_status_lamp_manager) --[hidden] (ad_status_lamp)
(/engage_button_manager) --[hidden] (engage_button)
(/warning_lamp_manager) --[hidden] (emergency_lamp)
(/warning_lamp_manager) ---[hidden] (warning_lamp)
(/ad_sound_manager) --[hidden] (speaker)

(/v2i_interface) <-- (/awapi/awapi_awiv_adapter_node)  : \n/awapi/tmp/infrastructure_commands
(/v2i_interface) -> (/awapi/awapi_awiv_adapter_node)  : /system/v2x/virtual_traffic_light_states
(/v2i_interface) --> (broadcasting device) : v2i command\n(UDP)
(/v2i_interface) <-- (broadcasting device) : v2i status\n(UDP)
(/v2i_command_muxer) <- (/vtl_adapter) : /v2i_gate/infrastructure_commands
(/vtl_adapter) <- (/autoware_state_machine)

(broadcasting device) --> (v2ictl_0)
(broadcasting device) <-- (v2ictl_0)
(broadcasting device) --> (v2ictl_1)
(broadcasting device) <-- (v2ictl_1)
(broadcasting device) --> (v2ictl_n)
(broadcasting device) <-- (v2ictl_n) : wireless communication

(/autoware_state_machine) --> (/ad_status_lamp_manager)
(/ad_status_lamp_manager) --> (/dio_ros_driver) : /dio/dout0

(/delivery_reservation_button_manager) <-- (/dio_ros_driver): /dio/din1
(/button_output_selector) <-- (/delivery_reservation_button_manager)
(/autoware_state_machine) <- (/button_output_selector)
(/shutdown_manager) <-d- (/button_output_selector)
(/engage_button_manager) <-- (/dio_ros_driver): /dio/din0
(/engage_srv_converter) <-- (/engage_button_manager)

(/autoware_state_machine) --> (/delivery_reservation_lamp_manager)
(/shutdown_manager) -d-> (/delivery_reservation_lamp_manager)
(/delivery_reservation_lamp_manager) --> (/dio_ros_driver) : /dio/dout3

(/autoware_state_machine) <-- (/engage_srv_converter)
(/autoware_state_machine) --> (/engage_srv_converter) 
(/control/vehicle_cmd_gate) <-- (/autoware_state_machine) : /api/autoware/set/engage\n /api/autoware/set/start_request
(/control/vehicle_cmd_gate) --> (/autoware_state_machine) 

(/awapi/awapi_awiv_adapter_node) -[hidden] (/control/vehicle_cmd_gate)
(/awapi/awapi_awiv_adapter_node) --> (/ad_sound_manager) : /awapi/vehicle/get/status
(/autoware_state_machine) ---> (/ad_sound_manager)
(/autoware_state_machine) <--- (/ad_sound_manager)
(/ad_sound_manager) --> (/sound_voice_alarm/audio_driver)
(/ad_sound_manager) <-- (/sound_voice_alarm/audio_driver)
(/ad_sound_manager) --> (/sound_bgm/audio_driver)
(/sound_voice_alarm/audio_driver) --> (speaker)
(/sound_bgm/audio_driver) --> (speaker)

(FMS) -> (DeliveryApp)
(FMS) <- (DeliveryApp)
(FMS) --> (Agent)
(FMS) <-- (Agent)
(Agent) -> (/go_interface) : /webauto/vehicle_info
(DeliveryApp) -->  (/go_interface) : result of GET API
(DeliveryApp) <-- (/go_interface) : request of GET API\nrequest of PATCH API

(broadcasting device) -[hidden] (v2ictl_1)
(v2ictl_0) -[hidden] (v2ictl_1)
(v2ictl_1) -[hidden] (v2ictl_n)
(v2ictl_n) --[hidden] (/ad_sound_manager)


(v2ictl_0) --> (v2ihw_0)
(v2ictl_0) <-- (v2ihw_0)
(v2ictl_1) --> (v2ihw_1)
(v2ictl_1) <-- (v2ihw_1)
(v2ictl_n) --> (v2ihw_n)
(v2ictl_n) <-- (v2ihw_n) : GPIO communication

(/autoware_state_machine) --> (/warning_lamp_manager)
(/warning_lamp_manager) --> (/dio_ros_driver) : /dio/dout2
(/warning_lamp_manager) --> (/dio_ros_driver) : /dio/dout1

(/dio_ros_driver) --> (ad_status_lamp)
(/dio_ros_driver) --> (warning_lamp)
(/dio_ros_driver) --> (emergency_lamp)
(/dio_ros_driver) --> (delivery_reservation_lamp)
(/dio_ros_driver) <-- (engage_button)
(/dio_ros_driver) <-- (delivery_reservation_button)

(/awapi/awapi_awiv_adapter_node) --> (/autoware_state_machine) : /awapi/autoware/get/status\n/awapi/vehicle/get/status

@enduml
